MusicStore/Controllers/AlbumManagementController.cs
using System.Collections.Generic;
using System.Linq;
using MusicStore.Models;
using MusicStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MusicStore.Controllers
{
    [Authorize(Roles = "Admin")]
    [Authorize(Policy = "DeleteAlbum")]
    public class AlbumManagementController : Controller
    {
        private readonly IAlbumRepository _AlbumRepository;
        private readonly ICategoryRepository _categoryRepository;

        public AlbumManagementController(IAlbumRepository AlbumRepository, ICategoryRepository categoryRepository)
        {
            _AlbumRepository = AlbumRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult Index()
        {
            var Albums = _AlbumRepository.Albums.OrderBy(p => p.AlbumId);
            return View(Albums);
        }

        public IActionResult AddAlbum()
        {
            var categories = _categoryRepository.Categories;
            var AlbumEditViewModel = new AlbumEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList(),
                CategoryId = categories.FirstOrDefault().CategoryId
            };
            return View(AlbumEditViewModel);
        }

        [HttpPost]
        public IActionResult AddAlbum(AlbumEditViewModel AlbumEditViewModel)
        {
            // Custom validation rules
            if (ModelState.GetValidationState("Album.Price") == ModelValidationState.Valid  &&
                AlbumEditViewModel.Album.Price < 0)
            {
                ModelState.AddModelError(nameof(AlbumEditViewModel.Album.Price),
                    "The price of the Album should be higher than 0.");
            }

            if (AlbumEditViewModel.Album.IsAlbumOfTheWeek && !AlbumEditViewModel.Album.InStock)
            {
                ModelState.AddModelError(nameof(AlbumEditViewModel.Album.IsAlbumOfTheWeek),
                    "Only Albums that are in stock should be Album of the Week.");
            }

            AlbumEditViewModel.Album.CategoryId = AlbumEditViewModel.CategoryId;

            //Basic validation
            if (ModelState.IsValid)
            {
                _AlbumRepository.CreateAlbum(AlbumEditViewModel.Album);
                return RedirectToAction("Index");
            }
            return View(AlbumEditViewModel);
        }


        //public IActionResult EditAlbum([FromRoute]int AlbumId)
        //public IActionResult EditAlbum([FromQuery]int AlbumId, [FromHeader] string accept)
        public IActionResult EditAlbum([FromQuery]int AlbumId, [FromHeader(Name = "Accept-Language")] string accept)
        {
            var categories = _categoryRepository.Categories;

            var Album = _AlbumRepository.Albums.FirstOrDefault(p => p.AlbumId == AlbumId);

            var AlbumEditViewModel = new AlbumEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList(),
                Album = Album,
                CategoryId = Album.CategoryId
            };

            var item = AlbumEditViewModel.Categories.FirstOrDefault(c => c.Value == Album.CategoryId.ToString());
            item.Selected = true;

            return View(AlbumEditViewModel);
        }

        [HttpPost]
        //public IActionResult EditAlbum([Bind("Album")] AlbumEditViewModel AlbumEditViewModel)
        public IActionResult EditAlbum(AlbumEditViewModel AlbumEditViewModel)
        {
            AlbumEditViewModel.Album.CategoryId = AlbumEditViewModel.CategoryId;

            if (ModelState.IsValid)
            {
                _AlbumRepository.UpdateAlbum(AlbumEditViewModel.Album);
                return RedirectToAction("Index");
            }
            return View(AlbumEditViewModel);
        }

        [HttpPost]
        public IActionResult DeleteAlbum(string AlbumId)
        {
            return View();
        }

        public IActionResult QuickEdit()
        {
            var AlbumNames = _AlbumRepository.Albums.Select(p => p.Name).ToList();
            return View(AlbumNames);
        }

        [HttpPost]
        public IActionResult QuickEdit(List<string> AlbumNames)
        {
            //Do awesome things with the Album names here
            return View(AlbumNames);
        }

        public IActionResult BulkEditAlbums()
        {
            var AlbumNames = _AlbumRepository.Albums.ToList();
            return View(AlbumNames);
        }

        [HttpPost]
        public IActionResult BulkEditAlbums(List<Album> Albums)
        {
            //Do awesome things with the Album here
            return View(Albums);
        }
    }
}

MusicStore/Views/AlbumManagement/AddAlbum.cshtml
@model AlbumEditViewModel

<h2>Create a new Album</h2>

<form asp-controller="AlbumManagement" asp-action="AddAlbum" method="post" class="form-horizontal" role="form">
    <h4>Enter the Album details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Album.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.Name" class="form-control" />
            <span asp-validation-for="Album.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.ShortDescription" class="form-control" />
            <span asp-validation-for="Album.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.LongDescription" class="form-control" />
            <span asp-validation-for="Album.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.Price" class="form-control" />
            <span asp-validation-for="Album.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.ImageThumbnailUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.ImageThumbnailUrl" class="form-control" />
            <span asp-validation-for="Album.ImageThumbnailUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.ImageUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.ImageUrl" class="form-control" />
            <span asp-validation-for="Album.ImageUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.InStock" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.InStock" class="form-control" />
            <span asp-validation-for="Album.InStock" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.IsAlbumOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.IsAlbumOfTheWeek" class="form-control" />
            <span asp-validation-for="Album.IsAlbumOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create Album" />
        </div>
    </div>
</form>

MusicStore/Views/AlbumManagement/BulkEditAlbums.cshtml
@model List<Album>

<form asp-action="BulkEditAlbums" method="post">
    @for (var i = 0; i < Model.Count; i++)
    {

        <div class="form-group">
            <label asp-for="@Model[i].AlbumId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="@Model[i].AlbumId" class="form-control" readonly="readonly" />
                <span asp-validation-for="@Model[i].AlbumId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="@Model[i].Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="@Model[i].Name" class="form-control" />
                <span asp-validation-for="@Model[i].Name" class="text-danger"></span>
            </div>
        </div>
    }
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MusicStore/Views/AlbumManagement/EditAlbum.cshtml
@model AlbumEditViewModel

<h2>Edit Album</h2>

<form asp-controller="AlbumManagement" asp-action="EditAlbum" method="post" class="form-horizontal" role="form">
    <h4>Update the Album details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Album.AlbumId" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.AlbumId" class="form-control" />@*readonly="readonly"*@
            <span asp-validation-for="Album.AlbumId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.Name" class="form-control" />
            <span asp-validation-for="Album.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.ShortDescription" class="form-control" />
            <span asp-validation-for="Album.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.LongDescription" class="form-control" />
            <span asp-validation-for="Album.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.Price" class="form-control" />
            <span asp-validation-for="Album.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.ImageThumbnailUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.ImageThumbnailUrl" class="form-control" />
            <span asp-validation-for="Album.ImageThumbnailUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.ImageUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.ImageUrl" class="form-control" />
            <span asp-validation-for="Album.ImageUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.InStock" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.InStock" class="form-control" />
            <span asp-validation-for="Album.InStock" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Album.IsAlbumOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Album.IsAlbumOfTheWeek" class="form-control" />
            <span asp-validation-for="Album.IsAlbumOfTheWeek" class="text-danger"></span>
        </div>
    </div>



    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Update Album" />
        </div>
    </div>
</form>

MusicStore/Views/AlbumManagement/Index.cshtml
@model IEnumerable<Album>

<h2>Album Management</h2>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">No Albums at this point :()</td></tr>
}
else
{
    <p>
        <a class="btn btn-primary" asp-action="AddAlbum">Add new Album</a>
        <a class="btn btn-primary" asp-action="QuickEdit">Edit Album names</a>
        <a class="btn btn-primary" asp-action="BulkEditAlbums">Edit Albums in bulk</a>
    </p>
    <table class="table table-condensed table-bordered">
        <tr>
            <th>Album ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>In stock</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        @foreach (var Album in Model)
        {
            <tr>
                <td>@Album.AlbumId</td>
                <td><img src="@Album.ImageThumbnailUrl" /></td>
                <td>@Album.Name</td>
                <td><input type="checkbox" asp-for="@Album.InStock" />
                <td>@Album.Price</td>
                <td>
                    <form asp-action="DeleteAlbum" asp-route-AlbumId="@Album.AlbumId" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditAlbum" asp-route-AlbumId="@Album.AlbumId">Edit</a>
                        <button type="submit" onclick="return confirm('Do you really want to delete this Album?');" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
    </table>
}
<p>
    <a class="btn btn-primary" asp-action="AddAlbum">Add new Album</a>
    <a class="btn btn-primary" asp-action="QuickEdit">Edit Album names</a>
    <a class="btn btn-primary" asp-action="BulkEditAlbums">Edit Albums in bulk</a>
</p>

MusicStore/Views/AlbumManagement/QuickEdit.cshtml
@model IList<string>

@if (Model.Count > 0)
{
    <form asp-action="QuickEdit" method="post">
        @for (var i = 0; i < Model.Count; i++)
        {
            <div class="form-group">
                <label>Album name @(i + 1):</label>
                <input id="AlbumNames" name="AlbumNames" asp-for="@Model[i]" class="form-control" />
            </div>
        }
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
}
else
{
    <h2>There aren't any Albums in the system</h2>
}