MusicStore/Models/Album.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MusicStore.Utility;
using Microsoft.AspNetCore.Mvc;

namespace MusicStore.Models
{
    public class Album
    {
        public int AlbumId { get; set; }

        [Display(Name = "Album Name")]
        public string Name { get; set; }

        [Display(Name = "Artist Name")]
        public string ShortDescription { get; set; }

        [Display(Name = "Description")]
        public string LongDescription { get; set; }
        public string AllergyInformation { get; set; }
        public decimal Price { get; set; }

        [ValidUrl(ErrorMessage = "That's not a valid URL")]
        public string ImageUrl { get; set; }

        [ValidUrl(ErrorMessage = "That's not a valid URL")]
        public string ImageThumbnailUrl { get; set; }
        public bool IsAlbumOfTheWeek { get; set; }
        public bool InStock { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }

        public virtual List<AlbumReview> AlbumReviews { get; set; }

        //Specific for Model Binding
        public SugarLevel SugarLevel { get; set; }

    }
}

MusicStore/ViewModels/AlbumViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicStore.ViewModels
{
    public class AlbumViewModel
    {
        public int AlbumId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public decimal Price { get; set; }
        public string ImageThumbnailUrl { get; set; }
    }
}

MusicStore/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using MusicStore.Models;
using MusicStore.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicStore.Controllers
{
    public class AlbumController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IAlbumRepository _AlbumRepository;
        private readonly IAlbumReviewRepository _AlbumReviewRepository;
        private readonly HtmlEncoder _htmlEncoder;


        public AlbumController( IAlbumRepository AlbumRepository, ICategoryRepository categoryRepository, IAlbumReviewRepository AlbumReviewRepository, HtmlEncoder htmlEncoder)
        {
            _categoryRepository = categoryRepository;
            _AlbumReviewRepository = AlbumReviewRepository;
            _htmlEncoder = htmlEncoder;
            _AlbumRepository = AlbumRepository;
        }

        
        public IActionResult Index()
        {
            return RedirectToAction("List",new {category = ""});
//            return List("");
        }

        public IActionResult List(string category)
        {
            return View(new AlbumsListViewModel
            {
                CurrentCategory = category??"All Albums"
            });
        }




        // [Route("[controller]/Details/{id}")]
        public IActionResult Details(int id)
        {
            var Album = _AlbumRepository.GetAlbumById(id);
            if (Album == null)
                return NotFound();

            return View(new AlbumDetailViewModel() { Album = Album });
        }



        // [Route("[controller]/Details/{id}")]
        [HttpPost]
        public IActionResult Details(int id, string review)
        {
            var Album = _AlbumRepository.GetAlbumById(id);
            if (Album == null)
                return NotFound();

            // Protect against XSS attacks by encoding all input
            string encodedReview = _htmlEncoder.Encode(review);

            _AlbumReviewRepository.AddAlbumReview(new AlbumReview() { Album = Album, Review = encodedReview });

            return View(new AlbumDetailViewModel() { Album = Album, Review="" });
        }

    }
}

MusicStore/Views/Album/Details.cshtml
@using System.Net
@using System.Threading.Tasks
@model AlbumDetailViewModel

<div class="thumbnail">
    <img alt="@Model.Album.Name" src="@Model.Album.ImageUrl">
    <div class="caption-full">
        <h3 class="pull-right">€@Model.Album.Price</h3>
        <h3>
            <a href="#">@Model.Album.Name</a>
        </h3>
        <h4>@Model.Album.ShortDescription</h4>
        <p>@Model.Album.LongDescription</p>
        <p class="button">
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
               asp-route-AlbumId="@Model.Album.AlbumId">Add to cart</a>
        </p>
    </div>
</div>

<h3>Reviews for this Album</h3>

@foreach (var review in @Model.Album.AlbumReviews)
{
    @*@Html.Raw(@review.Review)*@
    <div>@WebUtility.HtmlDecode(review.Review) </div>
    <hr />
}

<form asp-controller="Album" asp-action="Details" method="post" class="form-horizontal" role="form">
    <h4>Write a review</h4>
    <hr />
    <input type="hidden" asp-for="@Model.Album.AlbumId" />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Review" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Review" class="form-control" value="@Model.Review"/>
            <span asp-validation-for="Review" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Send review" />
        </div>
    </div>

</form>

MusicStore/Views/Album/List.cshtml
@model AlbumsListViewModel

@*<h1>@Model.CurrentCategory</h1>

    @foreach (var Album in Model.Albums)
    {
        @Html.Partial("AlbumOverviewSummary", Album)
    }*@


<h1>@Model.CurrentCategory Albums</h1>

<div id="AlbumDiv">
</div>



@section scripts
    {
    <script>

        $(document).ready(function () {
           LoadMoreAlbumsNext("@Model.CurrentCategory");
        });

        $(window).scroll(function() {
            if ($(window).scrollTop() + 1 >= $(document).height() - $(window).height()) {
                LoadMoreAlbumsNext("@Model.CurrentCategory");
            }

        });

        // closure function for paging loadmoreAlbums
        var LoadMoreAlbumsNext = (function() {
            var counter = 0;
            return function (category) {
                LoadMoreAlbums(category, counter);
                return counter += 1;
            }
        })();


        function LoadMoreAlbums(category, pageCounter) {
            $.ajax({
                type: 'GET',
                url: '/api/Albumdata/' + category  + '/' + pageCounter,
                dataType: 'json',
                success: function(jsonData) {
                    if (jsonData == null) {
                        alert('no data returned');
                        return;
                    }

                    $.each(jsonData,
                        function(index, Album) {

                            var AlbumSummarString = '<div class="col-sm-4 col-lg-4 col-md-4"> ' +
                                '  <div class="thumbnail">' +
                                '     <img src="' +
                                Album.imageThumbnailUrl +
                                '" alt="">' +
                                '      <div class="caption">' +
                                '         <h3 class="pull-right">€' +
                                Album.price +
                                '</h3>' +
                                '         <h3>' +
                                '             <a href=/Album/Details/' +
                                Album.albumId +
                                '>' +
                                Album.name +
                                '</a>' +
                                '         </h3>' +
                                '         <p><b>' +
                                Album.shortDescription +
                                '</b></p>' +
                                '    </div>' +
                                '    <div class="addToCart">' +
                                '        <p class="button">' +
                                '             <a class="btn btn-primary" href=/ShoppingCart/AddToShoppingCart?AlbumId=' +
                                Album.albumId +
                                '>Add to cart</a>' +
                                '         </p>' +
                                '     </div>' +
                                '  </div>' +
                                '</div>';

                            $('#AlbumDiv').append(AlbumSummarString);
                        });
                },
                error: function(ex) {
                    alert(ex);
                }
            });
            return false;
        }
    </script>


}